nginx:
    image: nginx:1.9
    volumes:
        - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    links:
        - fpm

fpm:
    build: docker/fpm
    volumes_from:
        - data

ruby:
    build: docker/ruby
    volumes_from:
        - data

php:
    build: docker/php
    volumes_from:
        - data

data:
    image: busybox
    volumes:
        - .:/var/www/html
        - ~/.composer:/var/www/.composer
