fpm:
    environment:
        SYMFONY_ENV: test

tools:
    environment:
        SYMFONY_ENV: test
    links:
       - phantomjs:phantomjs
       - chrome:chrome
       - firefox:firefox

phantomjs:
    image: cmfatih/phantomjs
    command: "--webdriver=4444"
    entrypoint: phantomjs

chrome:
    image: selenium/standalone-chrome:2.53.0
    volumes:
        - /dev/shm:/dev/shm

firefox:
    image: selenium/standalone-firefox:2.53.0
    volumes:
        - /dev/shm:/dev/shm
