app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api:
    resource: "."
    type:     "api"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/doc"
